spring:
  application:
    name: 'loja'
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
url:
  service:
    fornecedor: http://fornecedor

      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user


hystrix:  shareSecurityContext: true   